use_frameworks!

platform :ios, '9.0'

target 'Hi-Kit-Module_Example' do
  pod 'Hi-Kit-Module', :path => '../'
  pod 'Hi-Helper-Module', :path=>"../../Hi-Helper-Module"
  pod 'Hi-Router-Module', :path=>"../../Hi-Router-Module"
  target 'Hi-Kit-Module_Tests' do
    inherit! :search_paths

    
  end
end
